spring:
  profiles:
    active: local
  jackson:
    property-naming-strategy: SNAKE_CASE
  main:
    allow-circular-references: false
  jpa:
    hibernate:
      ddl-auto: none
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    primary:
      url: jdbc:mysql://localhost:3306/acore_auth
      username: root
      password: Loquendo96@
      driver-class-name: com.mysql.cj.jdbc.Driver
    secondary:
      url: jdbc:mysql://localhost:3306/acore_characters
      username: root
      password: Loquendo96@
      driver-class-name: com.mysql.cj.jdbc.Driver
    three:
      url: jdbc:mysql://localhost:3306/acore_world
      username: root
      password: Loquendo96@
      driver-class-name: com.mysql.cj.jdbc.Driver
server:
  address: 0.0.0.0
  port: 8090
application:
  credentials:
    command:
      username: 'admin'
      password: 'admin'
  account:
    api-key: ub6ygf417dmtkoq
    username: mschitiva68@gmail.com
    password: 'sebas'
  urls:
    wow-libre-login: http://localhost:8091/core/api/auth/login
    wow-libre-server: http://localhost:8091/core/api/server/key
  security:
    jwt:
      secret-key: A3F1E4B2D0A728C9F54D8B32C7A59A7D0B9A8F94D1F6C762E7DA56231988C158
      expiration: 604800000  # 7 day
      refresh-token:
        expiration: 1209600000 # 14 días
events:
  twinks:
     enable: false
google:
  api-secret: "6Ld2INkqAAAAAByGt40YkWgDIpkJQ1NE2oDVyyqb"
  api-key: "6Ld2INkqAAAAAD3-ikPyI-yzYgMoL6mvcQkAJak-"
server-web:
  name: "Wow Private Server"
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    primary:
      url: jdbc:mysql://localhost:3306/acore_auth
      username: ${DB_WOW_LIBRE_USERNAME}
      password: ${DB_WOW_LIBRE_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
    secondary:
      url: jdbc:mysql://localhost:3306/acore_characters
      username: ${DB_WOW_LIBRE_USERNAME}
      password: ${DB_WOW_LIBRE_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
    three:
      url: jdbc:mysql://localhost:3306/acore_world
      username: ${DB_WOW_LIBRE_USERNAME}
      password: ${DB_WOW_LIBRE_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
server:
  address: 0.0.0.0
  port: 8090
application:
  credentials:
    command:
      username: ${GM_USERNAME}
      password: ${GM_PASSWORD}
  account:
    api-key: ${API_KEY_WOW_LIBRE}
    username: ${USERNAME_WOW_LIBRE}
    password: ${PASSWORD_WOW_LIBRE}
  urls:
    wow-libre-login: https://api.wowlibre.com/core/api/auth/login
    wow-libre-server: https://api.wowlibre.com/core/api/server/key
  security:
    jwt:
      secret-key: ${SECRET_JWT}
      expiration: 604800000  # 7 day
      refresh-token:
        expiration: 1209600000 # 14 días
events:
  twinks:
    enable: ${EVENTS_TWINKS_ENABLE}
google:
  api-secret:  ${GOOGLE_API_SECRET}
  api-key: ${GOOGLE_API_KEY}
server-web:
  name: ${SERVER_WEB_NAME}